version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    container_name: grpc-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=test-grpc
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  app:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true

volumes: 
  db:
