version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=test-grpc
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes: 
  db:

networks:
  default:
    name: network-grpc
    external: true

