version: '3.8'

services:
  app:
    container_name: grpc-client
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    expose:
      - "3000"
    stdin_open: true
    tty: true

networks:
  default:
    name: network-grpc
    external: true